spring.application.name=busReserve

# === DataSource (PostgreSQL) ===
spring.datasource.url=jdbc:postgresql://localhost:5432/busReserve
spring.datasource.username=busReserve
spring.datasource.password=juan1082876634

# === JPA / Hibernate ===
# MUY IMPORTANTE: deja el esquema a cargo de Flyway
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Opcional (para ver SQL en consola)
# spring.jpa.show-sql=true

# === Flyway ===
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Si ya tienes tablas previas en la BD, activa baseline:
# spring.flyway.baseline-on-migrate=true
# Opcional si usas un esquema distinto a public:
# spring.flyway.schemas=public
# spring.flyway.default-schema=public
# Evitar borrados accidentales (recomendado en prod):
 spring.flyway.clean-disabled=false
